### ISSUE TITLE
I killed myself by shooting mystic flames as human, changing to undead, and then the flames hit me and killed me.

### ISSUE THREAD

**Issue by Suvanth-Erranki** [maitian352/Meadow-Guarder#179]
![image](https://user-images.githubusercontent.com/76885647/145733179-2bfa4a56-fb01-4310-ba7c-7f4400092712.png)

So I shot my mystic flames as human, changed to undead, and the flames hit me and killed me. So I managed to kill myself.

**Comment by Suvanth-Erranki** [comment]
![image](https://user-images.githubusercontent.com/76885647/145733917-3030f4e2-0a4c-492e-b349-8db09baa2787.png)

I did it again and I can confirm for a fact that this happens. If you shoot a projectile as a human and then change into undead, the projectile can kill you.

**Comment by Suvanth-Erranki** [comment]
Should this be considered a bug?

**Comment by Suvanth-Erranki** [comment]
![image](https://user-images.githubusercontent.com/76885647/145911534-e9dc95e7-736b-478e-b2c4-3fa294cb8d31.png)

I am still able to do this.

**Comment by maitian352** [comment]
Fixed. I made a typo.

**Comment by Suvanth-Erranki** [comment]
Not fixed.
![image](https://user-images.githubusercontent.com/76885647/145916728-ed0d616a-27b2-43d1-be2c-32c96a166247.png)

**Comment by maitian352** [comment]
Didn't update.
