### ISSUE TITLE
This isn't such a big issue but if you look closely, you start to see white lines running across the screen, which made me think my computer was cracked. I think this a tiling error - it isn't top priority, but I would consider changing the tiling so the white lines don't show.

### ISSUE THREAD

**Issue by Suvanth-Erranki** [maitian352/Meadow-Guarder#29]
Click and view the following image in a bigger tab and you will see the white lines.
![image](https://user-images.githubusercontent.com/63676047/97809275-ea076980-1c39-11eb-973a-73939787d1cb.png)

**Comment by maitian352** [comment]
Fixed.

**Comment by Suvanth-Erranki** [comment]
It's not fixed:
![image](https://user-images.githubusercontent.com/63676047/98730919-db852480-2394-11eb-9068-24baa1a9ae59.png)

**Comment by maitian352** [comment]
Didn't update yet.

**Comment by Suvanth-Erranki** [comment]
Okay.
