### ISSUE TITLE
just mowing my tree with a book

### ISSUE THREAD

**Issue by definitely-nobody-is-here** [maitian352/Meadow-Guarder#296]
![image](https://user-images.githubusercontent.com/67865358/123530188-ad571980-d6c5-11eb-9255-5ed411f34283.png)

**Comment by maitian352** [comment]
oh wait this is a bug with the map

**Comment by maitian352** [comment]
Fixed.

**Comment by definitely-nobody-is-here** [comment]
CAN YOU REOPEN IT ITS STILL NOT FIXED
![image](https://user-images.githubusercontent.com/67865358/123868033-2ab89f00-d8fd-11eb-8816-fceb71d12cea.png)

**Comment by maitian352** [comment]
The first tree is fixed.
