### ISSUE TITLE
Sometimes a monster spawns and its invisible.

### ISSUE THREAD

**Issue by Suvanth-Erranki** [maitian352/Meadow-Guarder#39]
Here is an image of a monster spawning invisible.
![image](https://user-images.githubusercontent.com/63676047/97869346-54beb080-1cdf-11eb-9971-c3923ff96a0e.png)

**Comment by maitian352** [comment]
Fixed.

**Comment by Suvanth-Erranki** [comment]
No, it is not fixed:

This happened right now:

![image](https://user-images.githubusercontent.com/63676047/97906545-daf3ea80-1d11-11eb-8a4d-9e84c215002b.png)

**Comment by maitian352** [comment]
Fixed.
